title: funnysunday
description: >
  
baseurl: "/"
url: "https://folium77.github.io"

author:
  name: kiyo
  github: folium77

sass:
  style: compressed

gems:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled: [year, categories]
  layouts: archive
  permalinks:
    year: '/jekyll/archives/year/:year/'
    categories: '/jekyll/category/:name/'
