title: 日暮れの音
description: "nightfall sounds"
  
baseurl: "/"
url: "https://funnysunday.com"

author:
  name: kiyo
  github: folium77

sass:
  style: compressed

gems:
  - jekyll-feed

feed:
  path: feed/index.xml